### ISSUE TITLE
Dependent template name issue (Clang 3.7.1)

### ISSUE THREAD

**Issue by nikelmwann** [dbralir/ginseng#18]
I get this error from `clang` when attempting to build Ginseng in my project:

```
ginseng/ginseng.hpp:197:41: error: use 'template' keyword to treat 'get' as a
      dependent template name
                if (auto com_info = eid.get<typename Traits::com>())
                                        ^
                                        template
```

There are four occurrences of this error throughout the file. I was able to fix them by adding the suggested `template` keyword like so:

```
if (auto com_info = eid.template get<typename Traits::com>())
```

If you'd like, I can turn this into a pull request. I'm not sure if this issue is limited to Clang (I didn't try compiling with GCC). From what I understand, the compiler just can't determine on its own whether get is a template or not.

**Comment by dbralir** [comment]
@nikelmwann I almost forgot about this issue, sorry about that! Thanks for reporting this.

The original code worked in GCC, but I have no idea why. It does report this error on other (simpler) code, but it seems to magically work for Ginseng.
